### ISSUE TITLE
Can't sign into xbox account, error code drowned

### ISSUE THREAD

**Issue by aqtoo** [Aetopia/BedrockUpdater#1]
I was able to get minecraft to open yet unable to sign into an xbox account, limiting my play to single player only, is that intentional of this project or is there something I'm missing? I installed via scoop.

OS : Windows 10 LTSC 2021

**Comment by Aetopia** [comment]
Please check out this support article:
https://help.minecraft.net/hc/en-us/articles/4404016313741-Error-Code-Troubleshooting-for-Minecraft-Bedrock-Edition

Make sure the follow Windows Services are running:

- Xbox Live Auth Manager
- Microsoft Sign-in Assistant
- Web Account Manager

Whatever this issue is not Bedrock Update related since it is only concerned with updating the game.

**Comment by aqtoo** [comment]
Apologies, fixed via enabling Xbox Live Auth Manager.
