### ISSUE TITLE
Suggestion: Integrate with Stonecutter

### ISSUE THREAD

**Issue by RuiNtD** [Aetopia/BedrockUpdater#3]
Hello. It would be nice if this had an option to integrate with [Stonecutter](https://github.com/Aetopia/Stonecutter) to automatically apply its fixes after updating and launching the game.

**Comment by Aetopia** [comment]
Thank you for the suggestion!

The latest update for Stonecutter no longer requires the dynamic link library to loaded at startup since it can re-create the swapchain if required.

As for integration, I would prefer if both projects remained separate.

Bedrock Updater just keeps the game up to date. It's ability to launch Minecraft is kept as a convenience feature so you can play as soon as possible.

In most cases, you won't be running Bedrock Updater frequently to launch MC but to check when an update is available.

As mentioned before, the latest update of Stonecutter can be injected at anytime so integration isn't required.
